carpentries/carpentrycon

- venue.md
Created a page where we can add all the information about the venue including accessibility and contact information.
> Created venue.md for venue and accessibility information

- ShortBio/SessionChairs/KariLJordan-bio.md
I still need to add the link to my session abstract once it's finished.
@malvikasharan
> Added short bio

- Sessions/2018-05-21/12-Pathways-of-Mentorship/Abstract.md
> Added mentoring abstract

- AtoZ_of_CarpentryCon.md
Not sure about it myself so be free to discard the changes. If you still look for a relevant X word and can push it a little, maybe replace 'Diversity' for 'Xenophobia, racism and all forms of intolerance'? (or link both sections)
> Proposal for X and correction of very minor typos

- AtoZ_of_CarpentryCon.md
I don't think welcome-team is right, so removed the hyphen i.e. "welcome team". But you may prefer to keep it, or (even better IMO) change it to "Welcome Team" :)
> Typo fixes

- Sessions/2018-06-01/05-Workshop-5-HPC-Carpentry/Abstract.md
@ChristinaLK could you please review this PR! Thanks.
> Hpccarpentry abstract WIP

- Sessions/2018-06-01/02-Workshop-2-Lesson-Hack-a-Thon-Voted-Session-From-Pitches/4OSS-lesson-development.md
adding lesson hackathon by ELIXIR
> Abstract for 4OSS lesson development

- Sessions/2018-05-30/12-Breakout-6-Diversity-And-Inclusion/Abstract.md
@malvikasharan please edit and merge:)
> Added D&I Session

- ShortBio/volunteers/JeanManguy.md
I don't have the rights to write to push my picture for the bio
> updates bio

- Sessions/2018-05-31/08-Lightning-Talks-Session-5/2-abstract-paula-andrea-martinez.md
> added leads

- program/lightning-talks.md
ELIXIR Training and the Carpentries @fpsom
> updating presenter ELIXIR Training and the Carpentries

- Sessions/2018-05-30/13-Poster-Session/abstract-alexander-konovalov.md
The abstract was initially submitted for the talk
> Replace talk->poster

- Sessions/2018-05-31/03-Skill-Up-6-Shell-Tips-And-Tricks/Abstract.md
Sorry. I had thought I had done this. Trying to tie up loose ends on my part for the conference. Edit as you see fit. I tried to keep it light.
> initial abstract

- AtoZ_of_CarpentryCon.md
sorry, meant to do these as a single PR -_-
> updated slack channel link

- Sessions/2018-05-30/13-Poster-Session/abstract-justin-millar.md
I added links to my presentation slides and poster under the Notes section.
> Add links to slides and poster

- Sessions/2018-05-30/04-Breakout-1-Carpentry-Methods-In-University-Courses/session_summary.md
> Adds notes of discussion points

- Sessions/2018-05-31/09-Lightning-Talks-Session-6/2-abstract-thor-wikfeldt.md
the slides are hosted on cicero.xyz
> add link to slides for thor's lightning talk

- Sessions/2018-06-01/06-Worksho-6-Library-Carpentry/Abstract.md
> Add LibCarp notes & presentation

- Minutes/2018-09-25-Community-Call.md
- Minutes/2018-10-23.md
- Minutes/2018-12-18.md
Fixed typing errors in the following meeting minutes:
2018-09-25
2018-10-23
2018-12-18
> Fixed typing errors in meeting minutes

- Minutes/2019-01-22.md
- Minutes/2019-02-05.md
- Minutes/minutes_template.md
Hi Fotis/Malvika,
Please let me know if the meeting minutes are not done correctly, so that I can fix it A.S.A.P.
Apologies for additional commits and revert - I was trying to update my repo from the master (I am not very good with Git/GitHub).
> Add meeting minutes 2019-02-05

- Minutes/2019-02-19.md
Kindly receive the minutes from the last CarpCon TF meeting
> minutes for the last call

- CarpentryCon-2020/Minutes/2019-05-14.md
Hi!  Adding the minutes from this week's meeting.  Please review and merge when you get a chance.
Thanks!
Sarah
> Minutes from the 2019-05-14 Meeting

- CarpentryCon-2020/Minutes/2019-09-03.md
MInutes for the CarpentryCon TF
> 2019-09-03.md 

- CarpentryCon-2020/Minutes/2019-10-01.md
Kindly review the minutes of the last CarpCon TF meeting
> minutes of call #20

- CarpentryCon-2020/Minutes/2019-10-15.md
> minutes from oct 15 meeting

- AtoZ_of_CarpentryCon.md
Added etherpad links for community call and CC volunteers
> Added etherpad links
